n1 = float(input("Enter Number-1:"))
n2 = float(input("Enter Number-2:"))

print(n1, "\t+\t", n2, "\t=\t", n1+n2)
print(n1, "\t-\t", n2, "\t=\t", n1-n2)
print(n1, "\t*\t", n2, "\t=\t", n1*n2)
print(n1, " \t/\t", n2, "\t=\t", n1/n2)
print(n1, "\t//\t", n2, "\t=\t", n1//n2)
print(n1, "\t%\t", n2, "\t=\t", n1%n2)
print(n1, "\t**\t", n2, "\t=\t", n1**n2)
